# Configuration for Travis (https://travis-ci.org)

language: objective-c

xcode_workspace: OneTimePassword.xcworkspace
xcode_scheme: OneTimePassword (iOS)

osx_image: xcode10.3

env:
  - RUNTIME="iOS 8.4"  DEVICE="iPhone 4s"
  - RUNTIME="iOS 9.3"  DEVICE="iPhone 6s"
  - RUNTIME="iOS 10.3" DEVICE="iPhone 7 Plus"
  - RUNTIME="iOS 11.4" DEVICE="iPhone X"
  - RUNTIME="iOS 12.4" DEVICE="iPhone XS Max"

# Include builds for watchOS
matrix:
  include:
    # Include several build-only jobs for watchOS
    - xcode_scheme: OneTimePassword (watchOS)
      env: BUILD_ONLY="YES" RUNTIME="watchOS 5.1" DEVICE="Apple Watch Series 4 - 44mm"
    - xcode_scheme: OneTimePassword (watchOS)
      env: BUILD_ONLY="YES" RUNTIME="watchOS 4.2" DEVICE="Apple Watch Series 3 - 38mm"
    - xcode_scheme: OneTimePassword (watchOS)
      env: BUILD_ONLY="YES" RUNTIME="watchOS 3.2" DEVICE="Apple Watch Series 2 - 42mm"
    - xcode_scheme: OneTimePassword (watchOS)
      env: BUILD_ONLY="YES" RUNTIME="watchOS 2.0" DEVICE="Apple Watch - 38mm"
    # Build with Carthage
    - env:
      before_script:
      script: carthage build --no-skip-current
    # Build with CocoaPods
    - env:
      before_script:
      script: pod lib lint --allow-warnings
    # Build with Xcode 10.1 and Swift 4.2
    - osx_image: xccode10.1
      env: RUNTIME="iOS 12.1" DEVICE="iPhone XR"
    # Build with CocoaPods and Swift 4.2
    - osx_image: xccode10.1
      env:
      before_script:
      script: pod lib lint --allow-warnings

before_script:
  - DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
  - RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
  - DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID)
  - xcrun simctl boot $DESTINATION_ID
  - if [[ $BUILD_ONLY == YES ]]; then ACTIONS="build"; else ACTIONS="build-for-testing test-without-building"; fi
  - echo "xcodebuild -workspace \"$TRAVIS_XCODE_WORKSPACE\" -scheme \"$TRAVIS_XCODE_SCHEME\" -destination \"id=$DESTINATION_ID\" $ACTIONS"

script: set -o pipefail && xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -destination "id=$DESTINATION_ID" $ACTIONS | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
